---
baseURL: ""
title: Pat's Bytes
paginate: 5
theme: PaperMod
defaultContentLanguage: en
weight: 1
cover:
  image: 'static/package_ansible.jpg'
params:
  title: Pat's Bytes
  description: "Welcome to my little bytes of learning"
  keywords: [Blog, PaperMod, Portforio]
  author: Pat Martin
  DateFormat: "January 1, 2001"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true

  homeInfoParams:
    Title: "Hello and welcome to Pat's Bytes"
    Content: 'Here I have collected "bytes" of knowledge to share or just remember later.'

menu:
  main:
    - identifier: articles
      name: Articles
      url: /articles/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 40

markup:
    highlight:
      # anchorLineNos: true
      codeFences: false
      guessSyntax: true
      style: monokai
...