baseURL: ""
title: Pat's Bytes
defaultContentLanguage: en
weight: 1
paginate: 5
theme: "ananke" 
feature_image: 'static/package_ansible.jpg'
params:
  show_reading_time: true
  description: "Just bytes of knowledge I have picked up as I go along"

menu:
  main:
    - identifier: articles
      name: Articles
      url: /articles/
      weight: 10
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 20
