---
baseURL: ""
title: Pat's Bytes
paginate: 5
theme: PaperMod
defaultContentLanguage: en
weight: 1
cover:
  image: 'static/package_ansible.jpg'
params:
  title: Pat's Bytes
  description: "Welcome to my little bytes of learning"
  keywords:
    - Blog
    - PaperMod
    - Portfolio
  author: Pat Martin
  DateFormat: "January 1, 2001"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true

  profileMode:
    enabled: true
    title: "Pat's Bytes" # optional default will be site title
    subtitle: "Welcome to my blog"
    imageUrl: "images/package_ansible.jpg" # optional
    imageTitle: "Pat's Bytes" # optional
    imageWidth: 360 # custom size
    imageHeight: 360 # custom size
    buttons:
      - name: Archive
        url: "/archive"
      - name: Articles
        url: "/articles"

menu:
  main:
    - identifier: articles
      name: Articles
      url: /articles/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 40

markup:
    highlight:
      codeFences: false
      guessSyntax: true
      style: monokai
...